#version: '3.9'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: plp123 
      POSTGRES_DB: plp_db
    ports:
      - 5432:5432
    volumes:
      # - ./data/postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Mount the SQL initialization script

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
